const he = {
  get_started: {
    title: "מצא וקנה ברכישה קבוצתית",
    sign_in_email: 'התחבר באמצעות דוא"ל',
    sign_in_google: `התחבר באמצעות גוגל`,
    not_member: `לא חבר?`,
    sign_up: `הירשם`,
  },
  sign_in: {
    title: `התחבר`,
    subtitle: `בוא נתחבר עם חשבון Teamcart שלך`,
    sign_in_apple: `התחבר באמצעות אפל`,
    sign_in_google: `התחבר באמצעות גוגל`,
    or_sign_in: `או התחבר באמצעות דוא"ל`,
    email: `דוא"ל`,
    password: `סיסמה`,
    sign_in: `התחבר`,
    forgot_password: `שכחת סיסמה?`,
    dont_have_account: `אין לך חשבון?`,
  },
  navs: {
    favourite: "מועדפים",
    groups: "הקבוצות שלי",
  },
  groups: {
    liked_items: "פריטים שאהבתי",
    discount_off: "הנחה",
    my_groups: "הקבוצות שלי",
    completed: `הושלם`,
    pending: `ממתין`,
    in_completed: `לא הושלם`,
    products: "מוצרים",
  },
  placeholder: {
    search: "חיפוש",
  },
  filter: {
    popular: `פופולרי`,
    man: `גבר`,
    dress: `שמלה`,
    woman: `אישה`,
    baby: `תינוק`,
    electronics: `אלקטרוניקה`,
  },
  product_detail: {
    product_details: "פרטי מוצר",
    size: "גודל",
    description: "תיאור",
    follow: "עקוב",
    more_details: "פרטים נוספים",
    brand: "מותג",
    size_fit: "מידה והתאמה",
    look_after_me: "טיפול במוצר",
    similar_products: "מוצרים דומים",
    price: "מחיר",
    join_group: "הצטרף לקבוצה",
    online_ago: "מחובר לפני שעה",
  },
  checkout: {
    checkout: "מעבר לקופה",
    delivery_location: "כתובת משלוח",
    andy_home: "הבית של אנדי",
    order_info: "פרטי הזמנה",
    free: "חינם",
    add: "הוסף",
    payment_method: "אמצעי תשלום",
    pay_now: "שלם עכשיו",
    sub_total: "סך ביניים",
    shipping: `משלוח`,
    total: `סך הכל`,
    order_successful: "ההזמנה בוצעה בהצלחה",
    success_desc: "לורם איפסום הוא טקסט דמה של תעשיית הדפוס והסדרי הדפוס.",
    continue: "המשך",
  },
};

export default he;
